# Generated by Django 2.2.6 on 2019-11-14 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OuiCheff', '0007_auto_20191114_1743'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reseipt_has_product',
            new_name='ReceiptHasProduct',
        ),
    ]
