# Generated by Django 2.2.6 on 2019-11-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OuiCheff', '0008_auto_20191114_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeToEat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_to_eat', models.CharField(choices=[('з', 'завтрак'), ('о', 'обед'), ('у', 'ужин'), ('п', 'перекус')], default=3, max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='receipt',
            name='time_to_eat',
            field=models.ManyToManyField(to='OuiCheff.TimeToEat'),
        ),
    ]
