# Generated by Django 2.2.6 on 2019-11-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OuiCheff', '0009_auto_20191114_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetoeat',
            name='time_to_eat',
            field=models.CharField(choices=[('з', 'завтрак'), ('о', 'обед'), ('у', 'ужин'), ('п', 'перекус'), ('оо', 'когда угодно')], default=3, max_length=1),
        ),
    ]
