# Generated by Django 2.2.6 on 2019-11-14 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OuiCheff', '0011_fridge'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReceiptHasProduct',
            new_name='ReceiptWithProduct',
        ),
    ]
