# Generated by Django 2.2.6 on 2019-11-14 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OuiCheff', '0013_auto_20191114_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridge',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='moderation',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='fridge',
            name='product',
        ),
        migrations.AddField(
            model_name='fridge',
            name='product',
            field=models.ManyToManyField(to='OuiCheff.Product'),
        ),
    ]
