# Generated by Django 2.2.6 on 2019-11-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OuiCheff', '0014_auto_20191114_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbohydrates',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='fats',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='proteins',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='carbohydrates',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='fats',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='proteins',
            field=models.FloatField(default=0),
        ),
    ]
