# Generated by Django 2.2.6 on 2019-11-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OuiCheff', '0015_auto_20191114_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='metric',
            field=models.CharField(choices=[('л', 'литры'), ('г', 'граммы'), ('шт', 'штуки')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='timetoeat',
            name='time_to_eat',
            field=models.CharField(choices=[('з', 'завтрак'), ('о', 'обед'), ('у', 'ужин'), ('п', 'перекус'), ('оо', 'когда угодно')], default=3, max_length=2),
        ),
    ]
