# Generated by Django 2.2.6 on 2019-11-14 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OuiCheff', '0016_auto_20191114_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fridge',
            name='product',
        ),
        migrations.AddField(
            model_name='fridge',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OuiCheff.Product'),
        ),
    ]
