# Generated by Django 2.2.6 on 2019-11-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OuiCheff', '0017_auto_20191114_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='metric',
            field=models.CharField(choices=[('л', 'милилитры'), ('г', 'граммы'), ('шт', 'штуки')], max_length=2, null=True),
        ),
    ]
