# Generated by Django 2.2.6 on 2019-11-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OuiCheff', '0018_auto_20191119_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='metric',
            field=models.CharField(choices=[('л', 'миллилитры'), ('г', 'граммы'), ('шт', 'штуки')], max_length=2, null=True),
        ),
    ]
