# Generated by Django 2.2.6 on 2019-12-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OuiCheff', '0019_auto_20191119_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='time_to_eat',
        ),
        migrations.AddField(
            model_name='receipt',
            name='time_to_eat',
            field=models.CharField(choices=[('з', 'завтрак'), ('о', 'обед'), ('у', 'ужин'), ('п', 'перекус'), ('оо', 'когда угодно')], default=3, max_length=2),
        ),
    ]
