# Generated by Django 2.2.6 on 2019-12-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OuiCheff', '0020_auto_20191204_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='time_to_eat',
            field=models.CharField(choices=[('з', 'завтрак'), ('о', 'обед'), ('у', 'ужин'), ('п', 'перекус'), ('оо', 'обед или ужин')], default=3, max_length=2),
        ),
    ]
